services:
  frontend:
    image: 764475167282.dkr.ecr.eu-north-1.amazonaws.com/gitsy-frontend:latest
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      backend:
        condition: service_started
    volumes:
      - /var/www/certbot:/var/www/certbot:ro
      - /var/letsencrypt:/etc/letsencrypt:ro

  backend:
    image: 764475167282.dkr.ecr.eu-north-1.amazonaws.com/gitsy-backend:latest
    expose:
      - "8000"
    environment:
      POSTGRES_USER: ${POSTGRES_PROD_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PROD_PASSWORD}
      POSTGRES_DB: ${POSTGRES_PROD_DB}
      DB_HOST: database
      GITHUB_TOKEN: ${GITHUB_TOKEN}
    depends_on:
      database:
        condition: service_healthy
      redis-db:
        condition: service_started

  database:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: ${POSTGRES_PROD_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PROD_PASSWORD}
      POSTGRES_DB: ${POSTGRES_PROD_DB}
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "pg_isready -U ${POSTGRES_PROD_USER} -d ${POSTGRES_PROD_DB}",
        ]
      interval: 5s
      timeout: 5s
      retries: 5
    volumes:
      - postgres-data:/var/lib/postgresql/data

  redis-db:
    image: redis:latest
    volumes:
      - redis-data:/var/lib/redis/data

volumes:
  postgres-data:
  redis-data:
