services:

  test-database:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
      POSTGRES_DB: gitsy_test_db


  redis-test-db:
    image: redis:latest


  test-runner:
    build:
      context: .
      dockerfile: Dockerfile.test
    depends_on:
      - test-database
      - redis-test-db
    command: tail -f /dev/null