services:

  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile.dev
    ports:
      - "8000:8000"
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
      POSTGRES_DB: gitsy_db
    depends_on:
      database:
        condition: service_healthy
    command: uvicorn --factory backend.main:create_app --host 0.0.0.0 --port 8000 --reload


  database:
    image: postgres:16-alpine
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
      POSTGRES_DB: gitsy_db
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 5s
      timeout: 5s
      retries: 5
    volumes:
      - postgres-data:/var/lib/postgresql/data


  redis-db:
    image: redis:latest
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/var/lib/redis/data


  pgadmin:
    image: dpage/pgadmin4
    ports:
      - "5050:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: password
    volumes:
      - pgadmin-data:/var/lib/pgadmin


volumes:
  postgres-data:
  redis-data:
  pgadmin-data: