import json
import redis.asyncio as redis
import backend.models as models
import backend.github_client as github_client
import backend.analysis_engine as analysis_engine
import backend.analysis_helpers as analysis_helpers

from sqlalchemy.orm import Session


async def create_postgres_report(repo_url: str, db: Session) -> int:
    """Adds the repository to postgres, creates a report and stores it postgres, then
        returns the report id.

    Args:
        repo_url (str): The URL of the repository in the format
                        https://github.com/owner/repo
        db (Session): The database session to talk to postgres.

    Returns:
        int: The id of the report in postgres.
    """
    owner, repo_name = github_client.get_owner_and_reponame(repo_url)
    repository = models.Repositories(repo_owner=owner, repo_name=repo_name)
    db.add(repository)

    report_raw = await analysis_engine.create_report(repo_url)

    report = models.Reports(
        commit_frequency=report_raw["commit_frequency"],
        code_churn=report_raw["code_churn"],
        issues_close_time=report_raw["issues_close_time"],
        pulls_close_time=report_raw["pulls_close_time"]
    )

    if repository is not None:
        report.repository = repository

    db.add(report)
    db.commit()
    db.refresh(report)

    return report.report_id


async def update_postgres_report(
    repo_url: str, db_report: models.Reports, db: Session
) -> None:
    """Updates the report in the database."""
    new_report = await analysis_engine.create_report(repo_url)
    db_report.commit_frequency = new_report["commit_frequency"]
    db_report.code_churn = new_report["code_churn"]
    db_report.issues_close_time = new_report["issues_close_time"]
    db_report.pulls_close_time = new_report["pulls_close_time"]
    db.add(db_report)
    db.commit()
    db.refresh(db_report)  # so Python has the timestamps generated by Postgres


async def create_redis_report(
        db_report: models.Reports, redis_report_id: str, r: redis.Redis, ttl: int
) -> None:
    serialised_code_churn = json.dumps(db_report.code_churn)
    iso_created_at = db_report.created_at.isoformat()
    iso_last_updated = db_report.last_updated.isoformat()

    await r.hset(
        redis_report_id,
        mapping={
            "report_id": db_report.report_id,
            "repo_id": db_report.repo_id,
            "commit_frequency": db_report.commit_frequency,
            "code_churn": serialised_code_churn,
            "issues_close_time": db_report.issues_close_time,
            "pulls_close_time": db_report.pulls_close_time,
            "created_at": iso_created_at,
            "last_updated": iso_last_updated
        },
    )

    await r.expire(redis_report_id, ttl)


async def update_redis_report(
    redis_report_id: str, db_report: models.Reports, r: redis.Redis, ttl: int
) -> None:
    serialised_code_churn = json.dumps(db_report.code_churn)
    iso_last_updated = db_report.last_updated.isoformat()
    mapping = {
        "commit_frequency": db_report.commit_frequency,
        "code_churn": serialised_code_churn,
        "issues_close_time": db_report.issues_close_time,
        "pulls_close_time": db_report.pulls_close_time,
        "last_updated": iso_last_updated
    }
    await r.hset(redis_report_id, mapping=mapping)
    await r.expire(redis_report_id, ttl)


def get_postgres_report_id(repo_url: str, db: Session) -> int | None:
    owner, repo_name = github_client.get_owner_and_reponame(repo_url)

    repo_id = (
        db.query(models.Repositories.repo_id)
        .filter(
            models.Repositories.repo_owner == owner,
            models.Repositories.repo_name == repo_name,
        )
        .scalar()
    )

    report_id = (
        db.query(models.Reports.report_id)
        .filter(
            models.Reports.repo_id == repo_id
        )
        .scalar()
    )

    return report_id


def get_postgres_report(postgres_report_id: int, db: Session) -> models.Reports | None:
    db_report = (
        db.query(models.Reports)
        .filter(
            models.Reports.report_id == postgres_report_id
        ).one()
    )

    return db_report


def get_redis_report_id(repo_url) -> str:
    owner, repo_name = github_client.get_owner_and_reponame(repo_url)
    return f"{owner}:{repo_name}"


async def get_redis_report(redis_report_id: str, r: redis.Redis) -> dict:
    redis_report = await r.hgetall(redis_report_id)
    redis_report["code_churn"] = json.loads(redis_report["code_churn"])
    redis_report["created_at"] = analysis_helpers.parse_timestamp(
        redis_report["created_at"]
    )
    redis_report["last_updated"] = analysis_helpers.parse_timestamp(
        redis_report["last_updated"]
    )
    return redis_report
