import backend.analysis_engine as analysis_engine
import backend.models as models
import redis.asyncio as redis
import asyncio

from sqlalchemy.orm import Session


async def create_db_report(
    repo_url: str, repository: models.Repositories = None
) -> models.Reports:
    report_raw = await asyncio.gather(
        analysis_engine.get_commit_frequency(repo_url),
        analysis_engine.get_code_churn(repo_url),
        analysis_engine.get_issues_close_time(repo_url),
        analysis_engine.get_pulls_close_time(repo_url),
    )

    report = models.Reports(
        commit_frequency=round(report_raw[0], 2),
        code_churn=report_raw[1],
        issue_times=round(report_raw[2], 2),
        pull_times=round(report_raw[3], 2),
    )

    if repository is not None:
        report.repository = repository

    return report


async def update_db_report(
    repo_url: str, db_report: models.Reports, db: Session
) -> None:
    """Updates the report in the database."""
    new_report = await create_db_report(repo_url)
    db_report.commit_frequency = new_report.commit_frequency
    db_report.code_churn = new_report.code_churn
    db_report.issue_times = new_report.issue_times
    db_report.pull_times = new_report.pull_times
    db.add(db_report)
    db.commit()
    db.refresh(db_report)  # so Python has the timestamps generated by Postgres


async def create_redis_report(db_report: models.Reports, r: redis.Redis) -> None:
    redis_report_name = f"reports:{db_report.report_id}"
    await r.hset(
        redis_report_name,
        mapping={
            "repo_id": db_report.repo_id,
            "commit_frequency": db_report.commit_frequency,
            "code_churn": db_report.code_churn,
            "issue_times": db_report.issue_times,
            "pull_times": db_report.pull_times,
            "created_at": db_report.created_at,
            "last_updated": db_report.last_updated,
        },
    )


async def update_redis_report(
    redis_report_id: str, db_report: models.Reports, r: redis.Redis
) -> None:
    redis_report = r.hgetall(redis_report_id)
    redis_report["commit_frequency"] = db_report.commit_frequency
    redis_report["code_churn"] = db_report.code_churn
    redis_report["issue_times"] = db_report.issue_times
    redis_report["pull_times"] = db_report.pull_times
    redis_report["last_updated"] = db_report.last_updated
    await r.expire(redis_report_id, 3600)


def get_repo_id(repo_url: str, db: Session) -> int | None:
    owner_and_repo = repo_url.removeprefix("https://github.com/")
    owner, _, repo_name = owner_and_repo.partition("/")
    repo_id = (
        db.query(models.Repositories.repo_id)
        .filter(
            models.Repositories.repo_owner == owner,
            models.Repositories.repo_name == repo_name,
        )
        .scalar()
    )
    return repo_id


def get_db_report(repo_id: int, db: Session) -> models.Reports | None:
    db_report = db.query(models.Reports).filter(models.Reports.repo_id == repo_id).one()
    return db_report
