FROM python:3.12-slim-bullseye

WORKDIR /app

COPY backend/requirements-dev.txt /app

RUN pip install -r requirements-dev.txt

COPY backend /app/backend

CMD ["uvicorn", "--factory", "backend.main:create_app", "--host", "0.0.0.0", "--port", "8000"]