FROM python:3.12-slim-bullseye

WORKDIR /app

COPY backend/requirements-prod.txt .

RUN pip install -r requirements-prod.txt

COPY backend .

RUN groupadd -r app && useradd -r -g app appuser
USER appuser

CMD ["uvicorn", "--factory", "backend.main:create_app", "--host", "0.0.0.0", "--port", "8000"]