FROM python:3.12-slim-bullseye

WORKDIR /app

COPY requirements-dev.txt .

RUN pip install -r requirements-dev.txt

COPY . .

CMD ["uvicorn", "--factory", "backend.main:create_app", "--host", "0.0.0.0", "--port", "8000"]