import pytest
import backend.models as models

from unittest.mock import patch
from backend.main import create_app
from contextlib import contextmanager
from sqlalchemy.orm import sessionmaker
from fastapi.testclient import TestClient
from sqlalchemy import create_engine, text


@pytest.fixture(scope="session")
def create_test_engine():
    """Connects to the database container, creates tables, then yields the connection.

    Returns:
        engine (Engine): the object that allows connection to the testing database.
    """

    # credentials copied directly from docker compose since this is for testing
    DB_USER = "admin"
    DB_PASSWORD = "password"
    DB_NAME = "gitsy_test_db"
    DB_HOST = "test-database"
    DATABASE_URL = (
        f"postgresql+psycopg2://{DB_USER}:{DB_PASSWORD}@{DB_HOST}:5432/{DB_NAME}"
    )

    engine = create_engine(DATABASE_URL)
    models.Base.metadata.create_all(bind=engine)
    yield engine

    # failsafe in case rollback fails or schema changes without restarting containers
    models.Base.metadata.drop_all(bind=engine)


@pytest.fixture()
def db_test_session(create_test_engine):
    """Opens a database session for testing, then rolls back all database changes.

    Args:
        create_test_engine: the engine connected to the testing database.

    Returns:
        session (Session): a session with the testing database.
    """
    engine = create_test_engine
    TestingSessionLocal = sessionmaker(autocommit=False, autoflush=False, bind=engine)

    connection = engine.connect()
    transaction = connection.begin()
    session = TestingSessionLocal(bind=connection)

    try:
        yield session
    finally:
        session.close()
        transaction.rollback()

        # primary keys are generated by postgres, transaction rollback won't reset them.
        # clearing tables would reset the sequences but only between testing sessions.
        # tests share the same engine, sequences accumulate across a testing session.
        # restarting the sequences between each database session guarantees consistency.
        connection.execute(text("ALTER SEQUENCE reports_report_id_seq RESTART"))
        connection.execute(text("ALTER SEQUENCE repositories_repo_id_seq RESTART"))
        connection.commit()
        connection.close()


@pytest.fixture()
def get_test_client(db_test_session):

    @contextmanager
    def postgres_test_context():
        yield db_test_session

    target_path = "backend.routers.reports.postgres_context"
    with patch(target=target_path, side_effect=postgres_test_context):
        app = create_app()
        client = TestClient(app)
        yield client
