import os
import pytest
from dotenv import load_dotenv

import backend.models as models

from fastapi.testclient import TestClient
from backend.database import get_db
from backend.main import create_app
from sqlalchemy.orm import sessionmaker
from sqlalchemy import create_engine, text


@pytest.fixture(scope="session")
def create_test_engine():
    # the credentials can be copied directly from docker composed because this code is not used for prod
    DB_USER = "admin"
    DB_PASSWORD = "password"
    DB_NAME = "gitsy_test_db"
    DB_HOST = "test-database"
    DATABASE_URL = (
        f"postgresql+psycopg2://{DB_USER}:{DB_PASSWORD}@{DB_HOST}:5432/{DB_NAME}"
    )

    engine = create_engine(DATABASE_URL)

    # this gets forwarded to the test database container via the above url
    models.Base.metadata.create_all(bind=engine)

    yield engine

    # failsafe in case rollback fails or schema changes without restarting the containers
    models.Base.metadata.drop_all(bind=engine)


@pytest.fixture()
def db_test_session(create_test_engine):
    engine = create_test_engine
    TestingSessionLocal = sessionmaker(autocommit=False, autoflush=False, bind=engine)

    connection = engine.connect()
    transaction = connection.begin()
    session = TestingSessionLocal(bind=connection)

    try:
        yield session
    finally:
        session.close()
        transaction.rollback()

        # primary keys are generated by postgres so transaction rollback won't reset them.
        # clearing tables would reset the sequences but only between testing sessions.
        # tests share the same engine, so the sequences accumulate across a testing session.
        # restarting the sequences between each database session guarantees consistency.
        connection.execute(text("ALTER SEQUENCE reports_report_id_seq RESTART"))
        connection.execute(text("ALTER SEQUENCE repositories_repo_id_seq RESTART"))
        connection.commit()
        connection.close()


@pytest.fixture()
def get_test_client(db_test_session):
    # .dependency_overrides needs a function as an argument - can't take a fixture
    def override_get_db():
        yield db_test_session

    app = create_app()
    app.dependency_overrides[get_db] = override_get_db

    client = TestClient(app)
    yield client
