FROM node:20-bullseye AS builder

WORKDIR /app

# install required packages for production
COPY package.json package-lock.json /app
RUN npm ci

COPY . /app

# create a user to only read+write in /app (for security)
RUN groupadd -r app && useradd -r -g app appuser
RUN chown -R appuser:app /app
USER appuser

RUN npm run build

FROM nginx:alpine AS runner

WORKDIR /usr/share/nginx/html

# copy the built files into nginx for serving
COPY --from=builder /app/dist /usr/share/nginx/html

COPY nginx.conf /etc/nginx/nginx.conf

EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]