events {}

http {
  include /etc/nginx/mime.types;
  default_type application/octet-stream;

  proxy_connect_timeout 10s;
  proxy_send_timeout 5s;
  proxy_read_timeout 10s;
  send_timeout 10s;

  server {
    listen 80;
    server_name gitsy.co.uk www.gitsy.co.uk;

    location /.well-known/acme-challenge/ {
      root /var/www/certbot;
      try_files $uri = 404;
    }

    location / {
      root /usr/share/nginx/html;
      try_files $uri /index.html;
    }
  }  
}