events {}  # default connection handling

http {
  include /etc/nginx/mime.types;  # maps file extensions appropriately so the browser recognises files
  default_type application/octet-stream;  # fallback for unrecognised file types

  # relating to locations passed by proxy_pass
  proxy_connect_timeout 10s;  # how long nginx waits to establish initial connection
  proxy_send_timeout 5s;  # how long nginx waits for a single write operation to finish
  proxy_read_timeout 10s;  # how long nginx waits for a response after a request
  send_timeout 10s;  # how long nginx waits for the browser to receive data 

  server {
    listen 80;  # listen for unencrypted traffic on port 80
    server_name gitsy.co.uk www.gitsy.co.uk;  # only accept requests from these domains

    location /.well-known/acme-challenge/ {  # route Let's Encrypt calls
      root /var/www/certbot;  # where certbot places a file that Let's Encrypt finds for validation
      try_files $uri = 404;  # return a 404 if the file isn't found
    }

    location / { # route all http requests to https 
      return 301 https://$host$request_uri;  # reconstruct url with https
    }
  }  

  server {
    listen 443 ssl; # listen on port 443
    http2 on;  # enable HTTP2
    server_name gitsy.co.uk www.gitsy.co.uk;  # only accept requests from these domains

    ssl_certificate /etc/letsencrypt/live/gitsy.co.uk/fullchain.pem;  # paths to certbot credentials
    ssl_certificate_key /etc/letsencrypt/live/gitsy.co.uk/privkey.pem;  # paths to certbot credentials

    ssl_session_timeout 1d;  # remember a user's session for 1 day to avoid recalculating encryption keys
    ssl_session_cache shared:SSL:20m;  # caches SSL handshakes so returning users connect faster
    ssl_protocols TLSv1.2 TLSv1.3;  # exclusively enable current industry standards
    ssl_prefer_server_ciphers on;  # ensures the best encryption supported by the browser is picked

    add_header Strict-Transport-Security "max-age=3600; includeSubDomains" always; # only allow HTTPS access

    location / {  # route generic requests  
      root /usr/share/nginx/html;  # where the built files are
      try_files $uri /index.html;  # SPA specific: hand index.html and route via JS when refreshing
    }

    location /api/ {  # route api requests
      proxy_pass http://backend:8000/;  # FastAPI container on the docker network

      proxy_set_header Host $host;  # pass the original domain name to FastAPI e.g. for validating origin
      proxy_set_header X-Real-IP $remote_addr;  # pass the IP of the user to FastAPI
      proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;  # list of IPs if the user is using proxies
      proxy_set_header X-Forwarded-Proto $scheme;  # tell FastAPI if the user is using HTTPS

      proxy_read_timeout 330s;  # override timeout for backend requests
    }
  }
}