name: CD

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: checkout repo
        uses: actions/checkout@v5

      - name: create backend and frontend images
        run: |
          docker build -f ./frontend/gitsy/Dockerfile.prod -t 764475167282.dkr.ecr.eu-north-1.amazonaws.com/gitsy-frontend:latest ./frontend/gitsy 
          docker build -f ./backend/Dockerfile.prod -t 764475167282.dkr.ecr.eu-north-1.amazonaws.com/gitsy-backend:latest ./backend

      - name: verify images
        run: docker images

      - name: set up aws credentials
        uses: aws-actions/configure-aws-credentials@v3
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-north-1

      - name: log in to AWS ECR
        run: |
          aws ecr get-login-password --region eu-north-1 | docker login --username AWS --password-stdin 764475167282.dkr.ecr.eu-north-1.amazonaws.com

      - name: push docker images
        run: |
          docker push 764475167282.dkr.ecr.eu-north-1.amazonaws.com/gitsy-frontend:latest
          docker push 764475167282.dkr.ecr.eu-north-1.amazonaws.com/gitsy-backend:latest

      - name: copy docker-compose.prod.yml into EC2
        uses: appleboy/scp-action@v1.0.0
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ec2-user
          key: ${{ secrets.EC2_SSH_KEY }}
          source: "docker-compose.prod.yml"
          target: "/home/ec2-user/"

      - name: deploy to EC2
        uses: appleboy/ssh-action@v1.2.2
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ec2-user
          key: ${{ secrets.EC2_SSH_KEY }}
          port: 22
          script: |
            aws ecr get-login-password --region eu-north-1 | docker login --username AWS --password-stdin 764475167282.dkr.ecr.eu-north-1.amazonaws.com
            export POSTGRES_PROD_USER=${{ secrets.POSTGRES_PROD_USER }}
            export POSTGRES_PROD_PASSWORD=${{ secrets.POSTGRES_PROD_PASSWORD }}
            export POSTGRES_PROD_DB=${{ secrets.POSTGRES_PROD_DB }}
            export GITHUB_TOKEN=${{ secrets.GIT_HUB_TOKEN }}
            
            POSTGRES_PROD_USER=$POSTGRES_PROD_USER \
            POSTGRES_PROD_PASSWORD=$POSTGRES_PROD_PASSWORD \
            POSTGRES_PROD_DB=$POSTGRES_PROD_DB \
            GITHUB_TOKEN=$GITHUB_TOKEN \
            docker compose -f docker-compose.prod.yml up -d --pull always

